# Generated by Django 3.2.5 on 2022-04-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image1',
        ),
    ]
