# Generated by Django 3.2.5 on 2022-04-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_image_category_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image1',
            new_name='image',
        ),
    ]
