# Generated by Django 3.2.5 on 2022-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(default=1000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image1',
            field=models.ImageField(blank=True, help_text='this field is only for the first parent(very important).', null=True, upload_to='site'),
        ),
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, help_text='this field is only for the first parent.', null=True, upload_to='site'),
        ),
        migrations.AddField(
            model_name='category',
            name='image3',
            field=models.ImageField(blank=True, help_text='this field is only for the first parent.', null=True, upload_to='site'),
        ),
    ]
