# Generated by Django 3.2.5 on 2022-03-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_auto_20220307_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder_line', models.CharField(blank=True, max_length=30, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=30, null=True)),
                ('arm', models.CharField(blank=True, max_length=30, null=True)),
                ('neck', models.CharField(blank=True, max_length=30, null=True)),
                ('bust_or_chest', models.CharField(blank=True, max_length=30, null=True)),
                ('breast_point', models.CharField(blank=True, max_length=30, null=True)),
                ('nipple_to_nipple', models.CharField(blank=True, max_length=30, null=True)),
                ('under_bust', models.CharField(blank=True, max_length=30, null=True)),
                ('shape', models.CharField(blank=True, max_length=30, null=True)),
                ('half_cut', models.CharField(blank=True, max_length=30, null=True)),
                ('top_length', models.CharField(blank=True, max_length=30, null=True)),
                ('gown_length', models.CharField(blank=True, max_length=30, null=True)),
                ('waist', models.CharField(blank=True, max_length=30, null=True)),
                ('hips_or_butt', models.CharField(blank=True, max_length=30, null=True)),
                ('laps', models.CharField(blank=True, max_length=30, null=True)),
                ('knees', models.CharField(blank=True, max_length=30, null=True)),
                ('half_length', models.CharField(blank=True, max_length=30, null=True)),
                ('base', models.CharField(blank=True, max_length=30, null=True)),
                ('down_length', models.CharField(blank=True, max_length=30, null=True)),
                ('custom_record', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
